# Import and Export : MySQL - Python

## MySQL - Import

In [46]:
#!pip install pymysql
#!pip install mysqlclient

In [47]:
#libraries
import pandas as pd
import pymysql
from sqlalchemy import create_engine
import os

In [48]:
print(pymysql.__version__)

2.2.8

In [49]:
F1 = 'C:/analytics/data/'
print(sorted(os.listdir(F1)))

['sqlpractise1.xlsx', 'studentsb2.csv']

In [50]:
folder1 = 'C:/analytics/data/'
file1 = "studentsb2.csv"

# Join folder and file name
file_path = os.path.join(folder1, file1)

if os.path.isfile(file_path):
    print(f"✅ File exists: {file_path}")
else:
    print(f"❌ File not found in {folder_path}")

✅ File exists: C:/analytics/data/studentsb2.csv

In [51]:
print(file_path)

C:/analytics/data/studentsb2.csv

In [52]:
df = pd.read_csv(file_path)
df.shape

(30, 6)

In [53]:
df.head()

,id,name,branch,score,exam_date,remarks
0,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
1,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
2,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
3,4,Keith Ferrell,Civil,75.00,2025-06-22,Average
4,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement

In [54]:
df.dtypes  # dates type NA

id             int64
name             str
branch           str
score        float64
exam_date        str
remarks          str
dtype: object

In [55]:
# dayfirst=False means 1st value is month if the value is between 1-12, otherwise between (11-31) it is day. 01/02/2023 means Jan1, but 25/02/2023 means Feb25.
# errors='coerce' will change the value with NAT(Not A Time)

df['exam_date'] = pd. to_datetime(df['exam_date'], dayfirst=False, errors='coerce') 
df.dtypes

id                    int64
name                    str
branch                  str
score               float64
exam_date    datetime64[us]
remarks                 str
dtype: object

In [58]:
engine1 = create_engine("mysql+pymysql://piuser:piit2026@localhost:3306/piit")
engine1

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [59]:
conn = engine1.connect()
print(conn)

<sqlalchemy.engine.base.Connection object at 0x000001EF20CCDA90>

In [15]:
pd.read_sql('SHOW DATABASES;', engine1)

             Database
0  information_schema
1               mysql
2  performance_schema
3                piit
4              sakila
5                 sys
6               world

In [16]:
# check
#pd.read_sql('SHOW DATABASES;', engine)

In [17]:
pd.read_sql('SHOW TABLES;', engine1)

               Tables_in_piit
0                      aelita
1                     authors
2                       books
3        customer_public_view
4      customer_sales_summary
5               customer_view
6              customerorders
7                   customers
8   east_region_sales_summary
9                  east_sales
10                  employees
11                math_scores
12         order_details_view
13                order_items
14                     orders
15         product_sales_view
16                   products
17       region_sales_summary
18                      sales
19                     sales1
20                     sales2
21         salesperson_totals
22             student_scores
23             student_totals
24                   students
25         subject_avg_scores
26                top_sellers

In [20]:
df.to_sql('students', engine1, if_exists='append', index=False, chunksize=1000, method='multi')

30

In [60]:
pd.read_sql('SHOW DATABASES;', engine1)

             Database
0  information_schema
1               mysql
2  performance_schema
3                piit
4              sakila
5                 sys
6               world

In [22]:
 # Students from csv imported in mysql database as students table

## Export from MySQL to csv/excel

In [23]:
# libraries
import pandas as pd
import pymysql
from sqlalchemy import create_engine
import os

In [26]:
# Engine - piuser#123
engine = create_engine('mysql+pymysql://piuser:piit2026@localhost:3306/piit')
print(engine)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [61]:
df2 = pd.read_sql("SELECT * FROM students", engine)
print(df2.shape)
df2.head()

(30, 6)

   id              name            branch  score  exam_date            remarks
0   1      Rick Johnson        Mechanical  63.68 2025-03-30            Average
1   2      Shannon Hall        Electrical  74.35 2024-03-28        Outstanding
2   3  Stephanie Flores  Computer Science  88.97 2024-05-17            Average
3   4     Keith Ferrell             Civil  75.00 2025-06-22            Average
4   5       Corey Allen  Computer Science  63.14 2025-05-17  Needs Improvement

In [62]:
df2.head(2)

   id          name      branch  score  exam_date      remarks
0   1  Rick Johnson  Mechanical  63.68 2025-03-30      Average
1   2  Shannon Hall  Electrical  74.35 2024-03-28  Outstanding

In [63]:
csvfile = 'C:/analytics/data/studentsb2.csv'
xlsfile =  'C:/analytics/data/sqlpractise1.xlsx'

In [64]:
print(os.listdir('C:/analytics/data/'))

['sqlpractise1.xlsx', 'studentsb2.csv']

In [65]:
df2.to_csv(csvfile, index=False)

In [66]:
df2.to_excel(xlsfile, index=False)

In [67]:
print(sorted(os.listdir('C:/analytics/data/'), key=str.lower))

['sqlpractise1.xlsx', 'studentsb2.csv']

In [68]:
# import data and check
df2b = pd.read_csv(csvfile)
df2b.shape

(30, 6)

In [69]:
df2c = pd.read_excel(xlsfile)
df2c.shape

(30, 6)