In [ ]:
# SQL - PYTHON Connect

In [1]:
#pip install sqlalchemy
#pip install pymysql

In [2]:
# libraries (install if required)
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [3]:
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
engine1 = create_engine("mysql+pymysql://root:Mysql%40123@localhost:3306/piit")
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
#engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
print(engine1)
#setting up connection mysql with user name - piuser, pwd - Pass@123 and to database piit at port no  3306

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [4]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [5]:
q("SELECT * FROM emp")

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dsal
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20.0,800.0
1,7499.0,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30.0,1900.0
2,7521.0,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30.0,1750.0
3,7566.0,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20.0,2975.0
4,7654.0,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30.0,2650.0
5,7698.0,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,NaN,30.0,2850.0
6,7782.0,CLARK,MANAGER,7839.0,1981-06-09,2450.0,NaN,10.0,2450.0
7,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,3000.0
8,7839.0,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10.0,5000.0
9,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,1500.0
10,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,1100.0
11,7900.0,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30.0,950.0
12,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,3000.0
13,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10.0,1300.0
14,1234.0,RITA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10.0,5000.0

In [6]:
q("select max(sal) from emp")

   max(sal)
0    5000.0